### ISSUE TITLE
鼠标模拟选择问题

### ISSUE THREAD

**Issue by AmnesiacGarden** [iyzyi/naraka_bladepoint_music#1]
6号更新之后界面多了一个麦克风选项 导致鼠标模拟选择乐谱错误

**Comment by iyzyi** [comment]
感谢反馈。该issue中提到的问题已修复（换一个坐标即可）
但是目前我发现新版本似乎更新了一些乐器的按键图案，我需要更多时间来测试脚本的通用性，预计今明两天合在一起更新。

**Comment by iyzyi** [comment]
已更新
