### ISSUE TITLE
一直报错，提示帧率不够，而且无论怎么修改都满

### ISSUE THREAD

**Issue by Szyslak666** [iyzyi/naraka_bladepoint_music#4]
一直报错，提示帧率不够，而且无论怎么修改都满

**Comment by Szyslak666** [comment]
> 一直报错，提示帧率不够，而且无论怎么修改都慢

**Comment by Szyslak666** [comment]
但是我有140多帧

**Comment by iyzyi** [comment]
笔记本还是台式机？尝试关闭无关软件，检查是否同时运行了两次脚本；

**Comment by Szyslak666** [comment]
> 笔记本还是台式机？ 尝试关闭无关软件；检查是否同时运行了两次脚本；尝试安装python环境后运行`python3 console.py`而不是带UI程序

笔记本，我就是运行的console.py，老哥
![Uploading 微信截图_20240725124925.png…]()

**Comment by Szyslak666** [comment]
![微信截图_20240725124925](https://github.com/user-attachments/assets/56cba0b7-5dca-4dc5-b22f-fa440a7a14d9)

**Comment by iyzyi** [comment]
是否是调试模式运行的

**Comment by Szyslak666** [comment]
是的，UI模式会卡死

**Comment by iyzyi** [comment]
我的意思是要直接运行，不要用调试模式

**Comment by iyzyi** [comment]
调试模式指的是debug，具体看你IDE的快捷键

**Comment by iyzyi** [comment]
提示帧率不够说明puautogui库截图 每秒小于20帧，不是指游戏帧率。如果你有台式机的话可以试下。

**Comment by Szyslak666** [comment]
没用调试模式，就是直接运行的

**Comment by iyzyi** [comment]
或者你试下关闭所有无关软件，游戏画质调为极低或低，游戏帧率改为60或75

**Comment by iyzyi** [comment]
画面设置可以参考 https://github.com/iyzyi/naraka_bladepoint_pve

**Comment by Szyslak666** [comment]
老师你这个征神的我也在用，征神全自动的没问题，用得好好的，画质已经调了，我再看一下后台吧
