### ISSUE TITLE
大佬，古筝用的是通用的延迟，需不需要修改呀

### ISSUE THREAD

**Issue by leux0** [iyzyi/naraka_bladepoint_music#5]
我修改延迟改了半天，古筝一直没反应，连普通3级难度考试都没过（只有优秀无完美）。后来查看代码才发现古筝用的是通用的延迟
![2024-08-15_151746](https://github.com/user-attachments/assets/76f91ebf-3d2c-41ba-af33-ee10439ae790)

**Comment by iyzyi** [comment]
那你就改通用的数值呗，或者把代码中**通用**这两个字改成**古筝**。我已经全红标了，代码就不更新了。

**Comment by iyzyi** [comment]
古筝的准确率相比其它几个乐器而言确实不够高，因为速度太快了。我一般古筝一局只能拿150熟练度。如果你能够在140~150左右，就不用再调了，基本到极限了。

**Comment by iyzyi** [comment]
另外如果你有代码基础，可以试着python3 console.py运行，而不是用带UI的程序，效率会好一些。同时，游戏内帧率不能太低也不能太高，建议开低特效（这个不是必要的），60或75帧率（这个强烈建议）。
